[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.16.0"

[[redirects]]
  from = "/bottleclocks"
  to = "/bottle-clocks"
  status = 301

[[redirects]]
  from = "/contactus"
  to = "/contact-us"
  status = 301

[[redirects]]
  from = "/contactus.htm"
  to = "/contact-us"
  status = 301

